export const seedData = {
  admins: [
    {
      id: "admin-001",
      name: "Alexander Sterling",
      email: "admin@notarix.io",
      password: "Admin@123456",
      role: "super_admin",
      isVerified: true,
      phone: "+1 (555) 123-4567",
      avatar: "/profile.jpg",
      forgotOtp: null,
      forgotOtpVerified: false,
      refreshToken: null,
      lastSignInAt: "2026-05-24T09:42:00.000Z",
    },
  ],
  requests: [
    {
      id: "req-1001",
      name: "Marcus Rivera",
      email: "m.rivera@notarix-partner.com",
      companyName: "Rivera Notary Services",
      phone: "+1-555-300-4001",
      contactType: "Notary Agent",
      requestType: "Platform Access",
      state: "Florida",
      message: "I would like to join the platform as an approved notary.",
      status: "Pending",
      createdAt: "2026-05-23T10:45:00.000Z",
    },
    {
      id: "req-1002",
      name: "Sarah Connor",
      email: "s.connor@firsttitle.com",
      companyName: "First Title Group",
      phone: "+1-555-300-4002",
      contactType: "Business",
      requestType: "Platform Access",
      state: "Texas",
      message: "Need client account access for title operations.",
      status: "Approved",
      createdAt: "2026-05-22T15:12:00.000Z",
    },
  ],
  users: [
    {
      id: "client-001",
      name: "Sarah Jenkins",
      email: "s.jenkins@example.com",
      role: "Client",
      company: "Acme Legal",
      area: "Texas",
      status: "Active",
      verification: "Approved",
      avatarTone: "bg-blue-100 text-blue-700",
      organization: {
        companyName: "Axiom Real Estate Group LLC",
        companyType: "Private Limited Company",
        website: "www.axiomrealestate.com",
      },
      address: {
        line1: "1200 Avenue of the Americas",
        city: "New York",
        state: "NY",
        zip: "10036",
        country: "United States",
      },
      primaryContact: {
        name: "Elena Rodriguez",
        email: "e.rodriguez@axiomre.com",
        phone: "+1 (555) 012-3456",
      },
      secondaryContact: {
        name: "David Chen",
        email: "d.chen@axiomre.com",
        phone: "+1 (555) 012-9876",
      },
      requiredDocuments: [
        { title: "Service Agreement", status: "Verified", file: "service_agreement.pdf" },
        { title: "W-9", status: "Pending", file: "w9_form.pdf" },
        { title: "Business License", status: "Missing", file: null },
      ],
      bankInfo: {
        bankName: "Chase Bank",
        routingNumberMasked: "********4412",
        accountNumberMasked: "********9845",
      },
    },
    {
      id: "notary-001",
      name: "Sarah Jenkins",
      email: "m.thorne@legalnotary.com",
      role: "Notary",
      company: "Sarah Jenkins",
      area: "Florida",
      status: "Pending",
      verification: "In Review",
      avatarTone: "bg-rose-100 text-rose-700",
      commission: {
        number: "NY-88291",
        state: "New York",
        expirationDate: "2026-10-24",
        travelRadius: "25 miles",
        coverageAreas: "Manhattan, Brooklyn",
      },
      address: {
        line1: "725 5th Ave",
        city: "New York",
        state: "NY",
        zip: "10022",
      },
      specialties: ["RON", "HELOC", "Purchase", "Seller Package"],
      payment: {
        bankName: "Chase Bank",
        routingNumberMasked: "********4412",
        accountNumberMasked: "********9845",
      },
      requiredDocuments: [
        { title: "Commission Certificate", status: "Verified", file: "commission_certificate.pdf" },
        { title: "Background Check", status: "Verified", file: "background_check.pdf" },
        { title: "Government ID", status: "Verified", file: "government_id.pdf" },
        { title: "ACH / Void Check", status: "Pending", file: "void_check.pdf" },
      ],
    },
    {
      id: "client-002",
      name: "Michael Chen",
      email: "m.chen@acmelegal.com",
      role: "Client",
      company: "Acme Legal",
      area: "Nationwide",
      status: "Pending",
      verification: "Pending",
      avatarTone: "bg-slate-200 text-slate-700",
    },
    {
      id: "client-003",
      name: "Elena Rodriguez",
      email: "elena.r@lexglobal.com",
      role: "Client",
      company: "Lex Global",
      area: "New York",
      status: "Suspended",
      verification: "Approved",
      avatarTone: "bg-rose-100 text-rose-700",
    },
  ],
  notaries: [
    {
      id: "notary-001",
      name: "Sarah Jenkins",
      location: "Travis County",
      radius: "50 mile radius",
      status: "Available",
      jobs: "142 Jobs Completed",
      tags: ["RON", "HELOC", "PURCHASE"],
      selected: true,
      avatarTone: "bg-emerald-100 text-emerald-700",
    },
    {
      id: "notary-002",
      name: "Michael Chen",
      location: "Travis County",
      radius: "25 mile radius",
      status: "Busy",
      jobs: "218 Jobs Completed",
      tags: ["RON", "COMMERCIAL"],
      selected: false,
      avatarTone: "bg-slate-200 text-slate-700",
    },
    {
      id: "notary-003",
      name: "Elena Rodriguez",
      location: "Williamson County",
      radius: "60 mile radius",
      status: "Available",
      jobs: "89 Jobs Completed",
      tags: ["ESTATE", "PURCHASE"],
      selected: false,
      avatarTone: "bg-rose-100 text-rose-700",
    },
  ],
  orders: [
    {
      id: "ORD-9421",
      route: "/orders/assigned",
      client: "First American Title",
      borrower: "John D. Smith",
      service: "Loan Refinance",
      location: "Austin, TX",
      schedule: "Apr 24, 2026 02:30 PM CST",
      notary: "Marcus Webb",
      notaryId: "notary-002",
      status: "Assigned",
      type: "In-Person",
      fee: "$150.00",
    },
    {
      id: "ORD-9420",
      route: "/orders/pending",
      client: "Zillow Home Loans",
      borrower: "Sarah Johnson",
      service: "Seller Package",
      location: "Denver, CO",
      schedule: "Apr 24, 2026 09:00 AM MST",
      notary: "Unassigned",
      notaryId: null,
      status: "Pending",
      type: "RON",
      fee: "$125.00",
    },
    {
      id: "RON-9418",
      route: "/orders/ron-session",
      client: "Rocket Mortgage",
      borrower: "Michael Chen",
      service: "Equity Line (HELOC)",
      location: "Seattle, WA",
      schedule: "Apr 24, 2026 04:45 PM PST",
      notary: "Elena Lopez",
      notaryId: "notary-003",
      status: "In Progress",
      type: "RON",
      fee: "$150.00",
    },
    {
      id: "ORD-9415",
      route: "/orders/completed",
      client: "Wells Fargo",
      borrower: "David Miller",
      service: "Power of Attorney",
      location: "Phoenix, AZ",
      schedule: "Apr 24, 2026 11:15 AM MST",
      notary: "Robert Hall",
      notaryId: "notary-001",
      status: "Completed",
      type: "In-Person",
      fee: "$195.00",
    },
  ],
  documents: [
    {
      id: "doc-001",
      name: "Loan_Agreement_V4.pdf",
      orderId: "ORD-88219",
      uploadedBy: "CLIENT",
      uploadedByLabel: "Sarah Jenkins",
      uploadedByColor: "bg-blue-50 text-blue-600",
      type: "PDF",
      date: "Apr 27, 2026",
      size: "2.4 MB",
      status: "Pending",
      icon: "file",
      iconColor: "text-rose-500",
      iconBg: "bg-rose-50",
      selected: true,
      notes: [
        {
          id: "note-001",
          author: "Sarah J.",
          message: "Please review the signature on page 4 specifically for the borrower's initials.",
          createdAt: "2h ago",
        },
      ],
      participants: ["Notary", "Admin", "Client"],
    },
    {
      id: "doc-002",
      name: "ID_Verification_Front.jpg",
      orderId: "ORD-90211",
      uploadedBy: "ADMIN",
      uploadedByLabel: "Admin Support",
      uploadedByColor: "bg-purple-50 text-purple-600",
      type: "Image",
      date: "Apr 27, 2026",
      size: "842 KB",
      status: "Verified",
      icon: "image",
      iconColor: "text-blue-500",
      iconBg: "bg-blue-50",
      selected: false,
      notes: [],
      participants: ["Admin", "Client"],
    },
    {
      id: "doc-003",
      name: "Notary_Seal_Certificate.pdf",
      orderId: "RON-9402",
      uploadedBy: "NOTARY",
      uploadedByLabel: "Robert Vance",
      uploadedByColor: "bg-emerald-50 text-emerald-600",
      type: "PDF",
      date: "Apr 27, 2026",
      size: "1.1 MB",
      status: "Rejected",
      icon: "file",
      iconColor: "text-rose-500",
      iconBg: "bg-rose-50",
      selected: false,
      notes: [],
      participants: ["Notary", "Admin"],
      rejectionReason: "Document watermark is obscuring the legal stamp. Please re-upload a clear copy.",
    },
  ],
  payments: [
    {
      id: "PAY-9920",
      reference: "TXN-88210",
      client: "Sarah Jenkins",
      note: "Order #NTX-90124 · Notary payout pending",
      type: "Outbound",
      amount: "$150.00",
      status: "Pending",
      date: "Apr 27, 2026",
      selected: true,
    },
    {
      id: "PAY-9921",
      reference: "TXN-88211",
      client: "First American Title",
      note: "Order #ORD-9421 · Client payment received",
      type: "Inbound",
      amount: "$225.00",
      status: "Paid",
      date: "Apr 26, 2026",
      selected: false,
    },
    {
      id: "PAY-9922",
      reference: "TXN-88212",
      client: "Lex Global",
      note: "Order #ORD-9415 · ACH failure",
      type: "Inbound",
      amount: "$185.00",
      status: "Failed",
      date: "Apr 25, 2026",
      selected: false,
    },
  ],
  messages: [
    {
      id: "conv-001",
      name: "Sarah Jenkins",
      role: "CLIENT",
      preview: "I’ve uploaded the ID front here. Can you please verify the quality?",
      unread: 2,
      time: "10:45 AM",
      active: true,
      statusLabel: "Client · Online",
      thread: [
        {
          id: "msg-001",
          from: "Sarah Jenkins",
          time: "10:30 AM",
          text: "Hello! I'm having trouble with the document upload for the power of attorney form. Does it need to be a PDF or will a high-res JPG work?",
          authorType: "user",
        },
        {
          id: "msg-002",
          from: "Admin Support",
          time: "10:32 AM",
          text: "Hi Sarah! A high-res JPG is perfectly fine as long as all four corners of the document are visible and the text is legible.",
          authorType: "admin",
        },
      ],
    },
    {
      id: "conv-002",
      name: "Marcus Rivera",
      role: "NOTARY",
      preview: "Need support with the live session camera handoff.",
      unread: 0,
      time: "09:10 AM",
      active: false,
      statusLabel: "Notary · Away",
      thread: [],
    },
  ],
  supportTickets: [
    {
      id: "tk-8821",
      name: "Marcus Rivera",
      type: "Licensed Notary",
      issue: "Digital Seal Sync Error",
      status: "In Progress",
      date: "Apr 27, 2026",
      priority: "High Priority",
    },
    {
      id: "tk-8822",
      name: "Sarah Jenkins",
      type: "Client",
      issue: "Document upload quality check",
      status: "Open",
      date: "Apr 27, 2026",
      priority: "Normal",
    },
  ],
  adminRows: [
    {
      id: "admin-row-001",
      name: "Alexander Sterling",
      email: "a.sterling@notarix.io",
      role: "Super Admin",
      status: "Active",
    },
    {
      id: "admin-row-002",
      name: "Maya Collins",
      email: "m.collins@notarix.io",
      role: "Admin",
      status: "Active",
    },
  ],
  notifications: [
    {
      id: "notif-001",
      title: "New Notary Registration Pending",
      meta: "2h ago - Needs review",
      action: "Review Application",
    },
    {
      id: "notif-002",
      title: "Payment Pending Verification",
      meta: "5h ago - Transaction #4402",
      action: "Review Payment",
    },
  ],
  siteClient: {
    stats: [
      { label: "TOTAL ORDERS", value: "124", trend: "+ 12% from last month", tone: "primary" },
      { label: "ACTIVE ORDERS", value: "12", trend: "6 due this week", tone: "warning" },
      { label: "COMPLETED ORDERS", value: "108", trend: "98% satisfaction rate", tone: "success" },
      { label: "PENDING ORDERS", value: "4", trend: "Awaiting signature", tone: "danger" },
    ],
    recentOrders: [
      { id: "26NC4999", type: "Remote Notarization", status: "In Progress", name: "John Smith", date: "Apr 24, 26" },
      { id: "26NC5001", type: "Document Signing", status: "Completed", name: "Sarah Connor", date: "Apr 25, 26" },
      { id: "26NC5002", type: "Affidavit Verification", status: "Pending", name: "Not Assigned", date: "Apr 26, 26" },
    ],
    documents: [
      "doc-001",
      "doc-002",
      "doc-003"
    ],
  },
  siteNotary: {
    stats: [
      { label: "Completed Total Assignments", value: "1,284" },
      { label: "Open Assignments", value: "04" },
      { label: "Total Earnings", value: "$14,205" },
    ],
    assignments: [
      { time: "09:30 AM", name: "Benjamin Richardson", detail: "Refinance - 42 Documents", status: "Confirmed", tone: "bg-emerald-50 text-emerald-600 border-emerald-100" },
      { time: "01:15 PM", name: "Elena Rodriguez", detail: "Power of Attorney", status: "In Progress", tone: "bg-blue-50 text-blue-600 border-blue-100" },
      { time: "04:00 PM", name: "Samuel Thompson", detail: "Home Equity Line of Credit", status: "Upcoming", tone: "bg-zinc-100 text-zinc-500 border-zinc-200" },
    ],
    requests: [
      { id: "ORD-4492", type: "RON Service", location: "Virtual - Online Platform", sub: "Nationwide Connectivity", date: "Oct 24, 2023 • 02:30 PM", zone: "Eastern Standard Time (EST)", amount: "$80", docs: "12 Pages", notes: "Loan modifications...", expires: "08:45" },
      { id: "ORD-4510", type: "In-Person", location: "Austin, TX", sub: "4.2 miles away", date: "Oct 25, 2023 • 10:00 AM", zone: "Central Standard Time (CST)", amount: "$125", docs: "45 Pages", notes: "Full closing docs...", expires: "15:20" },
    ],
    assignmentOrders: [
      { id: "RON-9402", orderType: "RON", title: "Sarah Mitchell", borrower: "Sarah Mitchell", location: "Austin, TX-12546", date: "Apr 24 2026", fee: "$150.00", status: "In Progress", tone: "bg-orange-50 text-orange-600", action: "Start Session" },
      { id: "IP-8210", orderType: "In-Person", title: "James Rodriguez", borrower: "James Rodriguez", location: "Miami, FL-12546", date: "Apr 24 2026", fee: "$225.00", status: "Pending", tone: "bg-amber-50 text-amber-600", action: "Accept" },
      { id: "RON-7104", orderType: "RON", title: "Elena Vance", borrower: "Elena Vance", location: "Seattle, WA12546", date: "Apr 24 2026", fee: "$150.00", status: "Completed", tone: "bg-emerald-50 text-emerald-600", action: "View" },
    ],
    assignmentOrderStats: [
      { label: "Total", value: "124", sub: "Assigned orders" },
      { label: "Pending", value: "12", sub: "Awaiting acceptance" },
      { label: "In Progress", value: "43", sub: "Currently active" },
      { label: "Completed", value: "69", sub: "Successfully signed" },
    ],
  },
};
